# Postwork Sesión 07

Construir varios algoritmos de clasificación basados en Machine Learning, y mostrar cuál es el mejor con base en evidencia sólida. Te invito a revisar la documentación de Sckit Learn para que revises los hiperparámetros y construyas distintos modelos.

#### Cancer Dataset

In [12]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
import numpy as np
from matplotlib import pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [2]:
dataset = load_breast_cancer()
x, y = dataset.data, dataset.target
df = pd.DataFrame(x, columns=dataset.feature_names)
print(df.head())

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0           

In [3]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

### Preprocesamiento


In [6]:
x_test, x_train, y_test, y_train = train_test_split(x, y, test_size = 0.30)
print(x_train.shape)
print(x_test.shape)

(171, 30)
(398, 30)


In [17]:
def calcularAccuracy(TP, TN, FP, FN):
    accuracy = (TP + TN) / (TP + TN + FP + FN)
    accuracy = accuracy * 100
    return accuracy

def calcularSensibilidad(TP, TN, FP, FN):
    sensibilidad = TP / (TP + FN)
    sensibilidad = sensibilidad * 100
    return sensibilidad

def calcularEspecificidad(TP, TN, FP, FN):
    especificidad = TN / (TN + FP)
    especificidad = especificidad * 100
    return especificidad

def evaluar(y_test, y_pred):
    resultado = confusion_matrix(y_test, y_pred)
    print(resultado)
    (TN, FP, FN, TP) = resultado.ravel()
    print("True positives: "+str(TP))
    print("True negatives: "+str(TN))
    print("False positives: "+str(FP))
    print("False negative: "+str(FN))
    
    acc = calcularAccuracy(TP, TN, FP, FN)
    sen = calcularSensibilidad(TP, TN, FP, FN)
    spec = calcularEspecificidad(TP, TN, FP, FN)
    print("Precision:"+str(acc.round(2))+"%")
    print("Sensibilidad:"+str(sen.round(2))+"%")
    print("Especificidad:"+str(spec.round(2))+"%")

### Naive Bayes


In [18]:
from sklearn.naive_bayes import GaussianNB

NaiveBayes = GaussianNB()
NaiveBayes.fit(x_train, y_train) 
y_pred_nb = NaiveBayes.predict(x_test) 
    
evaluar(y_test, y_pred_nb)

[[120  20]
 [  9 249]]
True positives: 249
True negatives: 120
False positives: 20
False negative: 9
Precision:92.71%
Sensibilidad:96.51%
Especificidad:85.71%


### Support Vector Machine

In [19]:
from sklearn.svm import SVC #Support Vector Classifier

SupportVectorMachine = SVC()
SupportVectorMachine.fit(x_train, y_train)
y_pred = SupportVectorMachine.predict(x_test)

evaluar(y_test, y_pred)

[[113  27]
 [  6 252]]
True positives: 252
True negatives: 113
False positives: 27
False negative: 6
Precision:91.71%
Sensibilidad:97.67%
Especificidad:80.71%


### Artificial Neuronal Network

In [20]:
from sklearn.neural_network import MLPClassifier

neurona4 = MLPClassifier(hidden_layer_sizes=(10,4),
                            max_iter=25000,
                            activation ='logistic',
                            tol= 1e-8)
    
neurona4.fit(x_train, y_train)
y_pred_4 = neurona4.predict(x_test)
print("¡Entrenamiento completado!")

¡Entrenamiento completado!


In [21]:
evaluar(y_test, y_pred_4)

[[131   9]
 [  5 253]]
True positives: 253
True negatives: 131
False positives: 9
False negative: 5
Precision:96.48%
Sensibilidad:98.06%
Especificidad:93.57%


### Random Forest

In [23]:
from sklearn.ensemble import RandomForestClassifier as forest

RandomForest = forest(n_estimators = 1500)
    
RandomForest.fit(x_train, y_train)
y_pred_rfc = RandomForest.predict(x_test)
print("¡Entrenamiento completado!")

¡Entrenamiento completado!


In [24]:
evaluar(y_test, y_pred_rfc)

[[126  14]
 [  7 251]]
True positives: 251
True negatives: 126
False positives: 14
False negative: 7
Precision:94.72%
Sensibilidad:97.29%
Especificidad:90.0%
